### ISSUE TITLE
[BUG] Coworkers leaves - I see teams I am not part of in the filter

### ISSUE THREAD

**Issue by nuyomi** [scavasoft/attendor-issues#11] opened 2021-10-13 08:14 UTC
![image](https://user-images.githubusercontent.com/22151745/137094082-616fb291-1d89-4022-8645-4eb6d92423bd.png)

**Comment by plamendp** [comment] 2021-10-15 17:47
For now it is "by design":  all users can see the whole organizational structure (units) and users assigned to those units.  Hence, "Coworkers".

**Closed as completed by plamendp** 2021-10-15 17:47 UTC
Labels: wontfix
